version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"   # raz w tygodniu
    labels: ["deps", "github-actions"]
    open-pull-requests-limit: 5

