name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Lint
        run: |
          poetry run ruff check .

      - name: Test
        run: |
          poetry run pytest -q --maxfail=1